name: Build

on:
  push:
    branches:
      - 'main'
    paths:
      - package.json
  pull_request:
    branches:
      - 'main'
    paths:
      - package.json

env:
  NODE_VERSION: 20
  PNPM_VERSION: 8

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Publish 🚀
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          pnpm publish --access public --no-git-checks



